echo "SETTING ALIASES"
alias a=alias
a h='history | cut -c 8-'
a la='ls -la'
a ll='ls -l'
a p=pwd
a lr='ls -lrt'
a m=more
a l=less
a mr='more README'
a cl=clear
a pt2=python2
a pt=python3
a atm=atom
a e=emacs
a mir='more ~/README'
alias me='m ~/emacs.txt'
alias via='vi ~/.bash_aliases'
alias vir='vi ~/README'
a ..='cd ../'
a ...='cd ../../'
a cw='ssh -Y alfreds@104.45.231.235 -p22'
a cdr='cd /opt/lampp/htdocs/'
a mu='m ~/used_commands.txt'
a n=nano
a mig='more ~/git.txt'
a cv='ssh -L 5918:127.0.0.1:5901 alfreds@104.40.25.223'
a cj='ssh -L 5915:127.0.0.1:5901 alfreds@40.85.185.185'
a myip='curl ipinfo.io/ip'
a pv='pip -V'
a xx='xterm -fa 'Monospace' -fs 10 -bg black -fg white&'
a xb='xterm -fa 'Monospace' -fs 10 -bg blue -fg white&'
a xr='xterm -fa 'Monospace' -fs 10 -bg red -fg white&'
a xg='xterm -fa 'Monospace' -fs 10 -bg darkgreen -fg white&'
